name: Bug Report
description: Report a bug in exporting, formatting, or extension behavior.
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Open account ...
        2. Click Export transactions ...
        3. Choose ...
        4. See error ...
    validations:
      required: true
  - type: input
    id: account_type
    attributes:
      label: Account Type
      placeholder: Cash, Credit Card, TFSA, RRSP, etc.
    validations:
      required: true
  - type: input
    id: transaction_type
    attributes:
      label: Transaction Type/Subtype (if known)
      placeholder: e.g. CREDIT_CARD/PURCHASE
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: payload
    attributes:
      label: Redacted Payload (optional)
      description: Remove names, account IDs, exact amounts, and personal identifiers.
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: Browser + version, extension version, OS.
